### ISSUE TITLE
The -l flag does not seem to be working.

### ISSUE THREAD

**Issue by funnyguygithub** [cduggn/ccExplorer#173] opened 2023-11-13 07:03 UTC
Hi There, 
as per readme: Refunds, discounts and credits are applied automatically. The -l flag should be used to exclude this behavior. But, it does not seem to be working as it's producing the same output and the same total with the flag and without it. 
thanks,
V

**Comment by cduggn** [comment] 2023-11-13 20:49
hey, can you share some more details so I can try and narrow down the issue;

- the exact command you are running (exclude any account specific details)
- how did you install the CLI (homebrew, docker, download the binary directly)

I've just pushed out a new [version ](https://github.com/cduggn/ccExplorer/releases/tag/v0.6.5) to pick up some dependency. The `-l` flag is working but maybe you have some combination of params I didn't consider

**Comment by funnyguygithub** [comment] 2023-11-13 22:37
1.  the CLIs:

`ccExplorer get aws -g DIMENSION=SERVICE,DIMENSION=OPERATION -p stdout -m MONTHLY -s 2023-10-01 -e 2023-10-31 -l`

or

`ccExplorer get aws -g DIMENSION=SERVICE,DIMENSION=OPERATION -p stdout -m MONTHLY -l`

there is no difference whether I opt the -l or not, the same total and for instance the monthly cost of the redshift is shown as 1.13 USD:

Amazon Redshift                         Not Applicable                   UnblendedCost  1.131588288      1.13      USD   MONTHLY      2023-10-01  2023-11-01 

CloudCraft picks up the cost of the RedShift as 

REDSHIFT Data warehouse $365.00 / то as well as AWS console at the billing account shows the credit.


on another account the cost of the RDS is the same with or with out -l:

Amazon Relational Database Service      CreateDBInstance:0012      UnblendedCost  1605.267096768  1605.27   USD   MONTHLY      2023-10-01  2023-10-31

and the same total. 


2. I did install it via home brew

`brew tap cduggn/cduggn & brew install ccExplorer`

version:

`❯ brew info ccExplorer
==> cduggn/cduggn/ccexplorer: stable 0.6.4

https://github.com/cduggn/ccexplorer
/opt/homebrew/Cellar/ccexplorer/0.6.4 (5 files, 14MB) *
  Built from source on 2023-11-12 at 22:11:19
From: https://github.com/cduggn/homebrew-cduggn/blob/HEAD/ccexplorer.rb`

**Comment by cduggn** [comment] 2023-11-14 09:01
that command shared is working for me but just to clarify, you are using the letter L (but  lowercase) right?

**Comment by funnyguygithub** [comment] 2023-11-14 15:44
Yes, it's L

echo "ccExplorer get aws -g DIMENSION=SERVICE,DIMENSION=OPERATION -p stdout -m MONTHLY -s 2023-10-01 -e 2023-10-31 -l" | tr a-z A-Z

CCEXPLORER GET AWS -G DIMENSION=SERVICE,DIMENSION=OPERATION -P STDOUT -M MONTHLY -S 2023-10-01 -E 2023-10-31 -L

^^^ "-L"

**Comment by cduggn** [comment] 2023-11-14 21:54
The current code base was missing a number of [charge types](https://docs.aws.amazon.com/cur/latest/userguide/Lineitem-columns.html) defined by AWS which may be applicable to your account. 

I've cut a new release [0.7.1] to include these.  Let me know if its still an issue after updating to the latest version -  `brew upgrade ccexplorer` . Failing that you may need to debug this to identify the nuances with your accounts discounts

**Comment by funnyguygithub** [comment] 2023-11-15 01:07
did not pick a new version from brew, unfortunately:

$ brew upgrade ccexplorer

Warning: cduggn/cduggn/ccexplorer 0.6.5 already installed

**Comment by cduggn** [comment] 2023-11-15 19:12
the [tap ](https://github.com/cduggn/homebrew-cduggn/blob/main/ccexplorer.rb) is up to date. Try the docker image or just run from source

**Comment by cduggn** [comment] 2023-11-18 14:18
@funnyguygithub if you were able to update to the latest version but are still having issues then it is most likely you are getting a discounted type that is not accounted for by the ccexplorer cli. You should be able find the discount types on your billing statement

**Comment by funnyguygithub** [comment] 2023-11-18 18:48
Yes, I was able to update to the latest version:

==> Upgrading cduggn/cduggn/ccexplorer
  0.6.5 -> 0.7.1
  
  Ran today:
 Warning: cduggn/cduggn/ccexplorer 0.7.1 already installed
 
 
Regrettably, the option -l (-L) didn't yield the desired results in my case. This was the sole functionality I had been seeking, as the other features appeared to be somewhat inconsequential to me.

**Comment by cduggn** [comment] 2023-11-19 17:09
If you are interested in finding the root cause add the following dimension filter to your request without the -l flag. This will provide us with more information about the charge type being associated with your Redshift instance. If that charge type value is not part of the already filtered list then we can add it and make the tool better for future users

ccExplorer get aws -g DIMENSION=SERVICE,DIMENSION=OPERATION -p stdout -m MONTHLY -s 2023-10-01 -e 2023-10-31

**Comment by funnyguygithub** [comment] 2023-11-20 07:57
Thank you. That's a slight improvement; at least it now displays the EC2 amount covered by SP. However, it still doesn't indicate which specific resource it covers


 -------------------------------------------------------------
` RANK  DIMENSION/TAG                           DIMENSION/TAG            METRIC NAME    AMOUNT           ROUNDED   UNIT  GRANULARITY  START       END

 1     Amazon Relational Database Service      Usage                    UnblendedCost  1605.3073318073  1605.31   USD   MONTHLY      2023-10-01  2023-10-31
 2     Amazon Elastic Compute Cloud - Compute  SavingsPlanCoveredUsage  UnblendedCost  604.8            604.80    USD   MONTHLY      2023-10-01  2023-10-31
 3     Tax                                     Tax                      UnblendedCost  193.55           193.55    USD   MONTHLY      2023-10-01  2023-10-31
 4     EC2 - Other                             Usage                    UnblendedCost  2.9033845343     2.90      USD   MONTHLY      2023-10-01  2023-10-31
 5     AmazonCloudWatch                        Usage                    UnblendedCost  1.0700929263     1.07      USD   MONTHLY      2023-10-01  2023-10-31
 6     Amazon DynamoDB                         Usage                    UnblendedCost  0.48672          0.49      USD   MONTHLY      2023-10-01  2023-10-31
 7     Amazon Elastic Compute Cloud - Compute  Usage                    UnblendedCost  0.0104946853     0.01      USD   MONTHLY      2023-10-01  2023-10-31
 8     Amazon Simple Storage Service           Usage                    UnblendedCost  0.0034662296     0.00      USD   MONTHLY      2023-10-01  2023-10-31
 9     AWS Key Management Service              Usage                    UnblendedCost  0.000006         0.00      USD   MONTHLY      2023-10-01  2023-10-31
 10    Amazon Virtual Private Cloud            Usage                    UnblendedCost  0                0.00      USD   MONTHLY      2023-10-01  2023-10-31

 11    Amazon Elastic Compute Cloud - Compute  SavingsPlanNegation      UnblendedCost  -604.8           -604.80   USD   MONTHLY      2023-10-01  2023-10-31`
  -------------------------------------------------------------
 

 
 on another account, the RedShift mystery is still a mystery:
 
 -------------------------------------------------------------
` RANK  DIMENSION/TAG                           DIMENSION/TAG            METRIC NAME    AMOUNT           ROUNDED   UNIT  GRANULARITY  START       END

 1     AWS Glue                                Usage                    UnblendedCost  12490.63108104   12490.63  USD   MONTHLY      2023-10-01  2023-10-31
 2     Amazon Simple Storage Service           Usage                    UnblendedCost  2103.5628341029  2103.56   USD   MONTHLY      2023-10-01  2023-10-31
 3     Tax                                     Tax                      UnblendedCost  1951.22          1951.22   USD   MONTHLY      2023-10-01  2023-10-31
 4     AmazonCloudWatch                        Usage                    UnblendedCost  1119.8264893624  1119.83   USD   MONTHLY      2023-10-01  2023-10-31
 5     AWS Database Migration Service          Usage                    UnblendedCost  171.2362114554   171.24    USD   MONTHLY      2023-10-01  2023-10-31
 6     Amazon Virtual Private Cloud            Usage                    UnblendedCost  90.0419771731    90.04     USD   MONTHLY      2023-10-01  2023-10-31
 7     EC2 - Other                             Usage                    UnblendedCost  38.9032288801    38.90     USD   MONTHLY      2023-10-01  2023-10-31
 8     Amazon Elastic Compute Cloud - Compute  SavingsPlanCoveredUsage  UnblendedCost  11.664           11.66     USD   MONTHLY      2023-10-01  2023-10-31
 9     AWS Secrets Manager                     Usage                    UnblendedCost  2.4046310804     2.40      USD   MONTHLY      2023-10-01  2023-10-31
 10    Amazon Redshift                         Usage                    UnblendedCost  1.09508544       1.10      USD   MONTHLY      2023-10-01  2023-10-31

 11    AWS Key Management Service              Usage                    UnblendedCost  0.96781692       0.97      USD   MONTHLY      2023-10-01  2023-10-31
 12    Amazon Athena                           Usage                    UnblendedCost  0.21506          0.22      USD   MONTHLY      2023-10-01  2023-10-31
 13    Amazon Elastic Compute Cloud - Compute  Usage                    UnblendedCost  0.0001013081     0.00      USD   MONTHLY      2023-10-01  2023-10-31
 14    AWS Lambda                              SavingsPlanCoveredUsage  UnblendedCost  0.0000118274     0.00      USD   MONTHLY      2023-10-01  2023-10-31
 15    AWS Lambda                              Usage                    UnblendedCost  0.0000084        0.00      USD   MONTHLY      2023-10-01  2023-10-31
 16    Amazon Simple Notification Service      Usage                    UnblendedCost  0.0000000184     0.00      USD   MONTHLY      2023-10-01  2023-10-31
 17    Amazon Redshift                         DiscountedUsage          UnblendedCost  0                0.00      USD   MONTHLY      2023-10-01  2023-10-31
 18    Amazon DataZone                         Usage                    UnblendedCost  0                0.00      USD   MONTHLY      2023-10-01  2023-10-31
 19    AWS Lambda                              SavingsPlanNegation      UnblendedCost  -0.0000118271    -0.00     USD   MONTHLY      2023-10-01  2023-10-31
 20    Amazon Elastic Compute Cloud - Compute  SavingsPlanNegation      UnblendedCost  -11.664          -11.66    USD   MONTHLY      2023-10-01  2023-10-31`
 
  -------------------------------------------------------------

**Comment by cduggn** [comment] 2023-11-20 19:59
This has helped me to understand some previously unsupported cost types.

The Cost Explorer API only supports grouping by two elements per request ( that can be two dimensions, two tags, or a mix of each) however you can use the filter argument to filter by a particular service which allows you to see very specific information for that service. It's not elegant when you need to check 10 or 20 services manually but you could always create a script to do the heavy lifting. This is an example which will let you see EC2 costs grouped by OPERATION and RECORD _TYPE

```bash
ccexplorer get aws -g DIMENSION=OPERATION,DIMENSION=RECORD_TYPE -f SERVICE="Amazon Elastic Compute Cloud - Compute"
```

**Comment by cduggn** [comment] 2023-11-24 09:28
I'll close this issue as it was party resolved by adding support for additional RECORD_TYPES (see below). The AWS API itself limits sorting to at most two dimensions or tags or a combination of each. This can still be overcome using the filter tag with either a specific service or using custom cost allocation tags which would offer finer granularity

```golang
Values: []string{"Refund", "Credit", "DiscountedUsage", "Discount", "BundledDiscount ", "SavingsPlanCoveredUsage", "SavingsPlanNegation"},
				},
```

**Closed by cduggn** 2023-11-24 09:28 UTC
